apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cli-env-reader
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cli-env-reader
  template:
    metadata:
      labels:
        app: java-cli-env-reader
    spec:
      containers:
        - name: java-cli-env
          image: "{{IMAGE_ID}}"
          imagePullPolicy: Always
          command: ["/opt/java/openjdk/bin/java", "Main"]
          args: ["arg1", "arg2"]
          volumeMounts:
            - name: config-volume
              mountPath: /config/configs.yaml
              subPath: configs.yaml
            - name: secret-volume
              mountPath: /config/secrets
              subPath: secrets
      imagePullSecrets:
        - name: {{PULLSECRET}}
      volumes:
        - name: config-volume
          configMap:
            name: java-cli-env-config
        - name: secret-volume
          secret:
            secretName: java-cli-env-secret
