apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: arg-env             # will become ./petclinic.json
spec:
  protected_image:    {{REPO}}:{{TAG}}
  unprotected_image:        {{REPO}}:{{TAG}} # SGX
  enforce:           ["/opt/java/openjdk/bin/java"] # SGX
{{IF_CVM}}
  tdx: true
{{END_IF}}

---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: arg-env
spec:
  # Inline‑selection: pick *only* the Deployment named “flask-server”
  file:
    - name: java-cli-env-reader
    - name: java-cli-env-secret
    - name: java-cli-env-config

  output_manifest_file: "./generated/manifest.cleaned.yaml"
  output_session_file: "./generated/manifest.session.yaml"
  cas_address:
    address: {{CAS_ADDR}} # default: cas.default
  manifest_env:
    - { name: SCONE_VERSION,  value: "1" }
    - { name: SCONE_LOG,      value: "FATAL" }
    - { name: SCONE_HEAP,      value: "4G" }
{{IF_CVM}}
    - { name: SCONE_CAS_ADDR, value: {{CLUSTER_ADDR}} }
{{END_IF}}

  session_env:
    - { name: LD_LIBRARY_PATH, value: /opt/java/openjdk/lib/server:/opt/java/openjdk/lib:/opt/java/openjdk/../lib }
  permissive: true 
{{IF_CVM}}
  tdx: true
  split: true
  kata-config-path: "./confidential/initidata.yaml"
{{END_IF}}
