
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: arg-env
{{NAMESPACE}}
spec:
  # Inline‑selection: pick *only* the Deployment
  label:
    - name: java-cli-env-reader
    - name: java-cli-env-secret
    - name: java-cli-env-config
  unique_app_id: scgz45kf51
  output_manifest_file: "./generated/manifest.sanitized.yaml"
  output_session_file: "./generated/manifest.session.yaml"
  cas_address:
    address: {{CAS_ADDR}} # default: cas.default
  manifest_env:
    - { name: SCONE_VERSION,  value: "1" }
    - { name: SCONE_LOG,      value: "FATAL" }
    - { name: SCONE_HEAP,     value: "2G" }
    - { name: SCONE_ALLOW_DLOPEN, value: "1" }
    - { name: SCONE_EDMM_MODE, value: "auto" }
    - { name: SCONE_SYSLIBS, value: "1" }
{{IF_CVM}}
    - { name: SCONE_CAS_ADDR, value: {{CLUSTER_ADDR}} }
{{END_IF}}

  session_env:
    - { name: LD_LIBRARY_PATH, value: /opt/java/openjdk/lib/server:/opt/java/openjdk/lib:/opt/java/openjdk/../lib }
    - { name: SCONE_METRICS, value: "prometheus_port:9999" }
  permissive: false
  {{SPLIT}}
{{IF_CVM}}
  tdx: true
  kata_config_path: "./generated/initidata.yaml"
  compress_kata_config: "Gzip"
{{END_IF}}
